# {{{
# Generated by zgen.
# This file will be overwritten the next time you run zgen save!

ZSH=$HOME/.zgen/robbyrussell/oh-my-zsh-master

# ### General modules
#source "$HOME/.zgen/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.plugin.zsh"
#source "$HOME/.zgen/zsh-users/zsh-history-substring-search-master/zsh-history-substring-search.zsh"
#source "$HOME/.zgen/b4b4r07/zsh-vimode-visual-master/zsh-vimode-visual.zsh"
#source "$HOME/.zgen/Tarrasch/zsh-bd-master/bd.plugin.zsh"
#source "$HOME/.zgen/dottr/dottr-master/dottr.plugin.zsh"
#source "$HOME/.zgen/rupa/z-master/z.sh"
#source "$HOME/.zgen/robbyrussell/oh-my-zsh-master/plugins/web-search/web-search.plugin.zsh"

# ### Plugins & Completions
#fpath=($HOME/.zgen/zsh-users/zsh-syntax-highlighting-master $HOME/.zgen/zsh-users/zsh-history-substring-search-master $HOME/.zgen/b4b4r07/zsh-vimode-visual-master $HOME/.zgen/Tarrasch/zsh-bd-master $HOME/.zgen/dottr/dottr-master $HOME/.zgen/rupa/z-master $HOME/.zgen/robbyrussell/oh-my-zsh-master/plugins/docker $HOME/.zgen/robbyrussell/oh-my-zsh-master/plugins/web-search ${fpath})

# }}}
